#!/bin/bash
# Writteb by ksaadDE 16.01.2023 
# compare two filelists and check what's missing in the current dir

# input difffiles.txt generated by e.g. find ./ 2>/dev/null > out.txt
# output is a positive message, if no missing files found otherwise it shows per line what's missing

# check if first parameter e.g. difffiles.txt is missing
if [ -z "$1" ]; then
	echo "[err]: you need to enter the first param as diff file e.g. generated by using find ./ 2>/dev/null > out.txt";
	exit
fi

foundsomething=""

# loop through the filepath+name lines in difffiles.txt ($1)
while IFS= read -r -u3 line; do
	if [ ! -f "$line" ]; then
		echo "[+] file '$line' missing";
		foundsomething="1"
	fi
done 3< "$1"

# positive message - if no differences found
if [ ! -z "$foundsomething" ]; then
	echo "[+] No files missing, seemingly";
fi
